const pokeTyping = {
    bug: {
        color: '#A6B91A',
        veryEffective: ['Dark', 'Grass', 'Psychic'],
        notVeryEffective: ['Fighting', 'Fire', 'Flying', 'Ghost', 'Poison', 'Steel'],
        weakAgainst: ['Fire', 'Flying', 'Rock'],
        immuneTo: [],
    },
    dark: {
        color: '#705746',
        veryEffective: ['Ghost', 'Psychic'],
        notVeryEffective: ['Dark', 'Fairy', 'Fighting'],
        weakAgainst: ['Bug', 'Fairy', 'Fighting'],
        immuneTo: ['Psychic'],
    },
    dragon: {
        color: '#6F35FC',
        veryEffective: ['Dragon'],
        notVeryEffective: ['Steel'],
        weakAgainst: ['Dragon', 'Fairy', 'Ice'],
        immuneTo: [],
    },
    ice: {
        color: '#96D9D6',
        veryEffective: ['Dragon', 'Flying', 'Grass', 'Ground'],
        notVeryEffective: ['Fire', 'Ice', 'Steel', 'Water'],
        weakAgainst: ['Fighting', 'Fire', 'Rock', 'Steel'],
        immuneTo: [],
    },
    electric: {
        color: '#F7D02C',
        veryEffective: ['Flying', 'Water'],
        notVeryEffective: ['Dragon', 'Electric', 'Grass'],
        weakAgainst: ['Grass'],
        immuneTo: [],
    },
    fairy: {
        color: '#D685AD',
        veryEffective: ['Dark', 'Dragon', 'Fighting'],
        notVeryEffective: ['Dragon', 'Electric', 'Grass'],
        weakAgainst: ['Poison', 'Steel'],
        immuneTo: ['Dragon'],
    },
    fighting: {
        color: '#C22E28',
        veryEffective: ['Dark', 'Ice', 'Normal', 'Rock', 'Steel'],
        notVeryEffective: ['Bug', 'Fairy', 'Flying', 'Poison', 'Psychic'],
        weakAgainst: ['Fairy', 'Flying', 'Psychic'],
        immuneTo: [],
    },
    fire: {
        color: '#EE8130',
        veryEffective: ['Bug', 'Grass', 'Ice', 'Steel'],
        notVeryEffective: ['Dragon', 'Fire', 'Rock', 'Water'],
        weakAgainst: ['Ground', 'Rock', 'Water'],
        immuneTo: [],
    },
    flying: {
        color: '#A98FF3',
        veryEffective: ['Bug', 'Fighting', 'Grass'],
        notVeryEffective: ['Electric', 'Rock', 'Steel'],
        weakAgainst: ['Electric', 'Ice', 'Rock'],
        immuneTo: ['Ground'],
    },
    ghost: {
        color: '#735797',
        veryEffective: ['Ghost', 'Psychic'],
        notVeryEffective: ['Dark'],
        weakAgainst: ['Dark','Ghost'],
        immuneTo: ['Normal'],
    },
    grass: {
        color: '#7AC74C',
        veryEffective: ['Ground', 'Rock', 'Water'],
        notVeryEffective: ['Bug', 'Fire', 'Flying', 'Grass', 'Poison', 'Steel'],
        weakAgainst: ['Bug', 'Fire', 'Flying', 'Ice', 'Poison'],
        immuneTo: [],
    },
    ground: {
        color: '#E2BF65',
        veryEffective: ['Electric', 'Fire', 'Poison', 'Rock', 'Steel'],
        notVeryEffective: ['Bug', 'Grass'],
        weakAgainst: ['Grass', 'Ice', 'Water'],
        immuneTo: ['Electric'],
    },
    normal: {
        color: '#A8A77A',
        veryEffective: [],
        notVeryEffective: ['Rock', 'Steel'],
        weakAgainst: ['Fighting'],
        immuneTo: [],
    },
    poison: {
        color: '#A33EA1',
        veryEffective: ['Fairy', 'Grass'],
        notVeryEffective: ['Poison', 'Ghost', 'Ground', 'Rock'],
        weakAgainst: ['Ground', 'Psychic'],
        immuneTo: [],
    },
    psychic: {
        color: '#F95587',
        veryEffective: ['Fairy', 'Grass'],
        notVeryEffective: ['Steel', 'Psychic'],
        weakAgainst: ['Bug', 'Dark', 'Ghost'],
        immuneTo: [],
    },
    rock: {
        color: '#B6A136',
        veryEffective: ['Bug', 'Fire', 'Flying', 'Ice'],
        notVeryEffective: ['Fighting', 'Ground', 'Steel'],
        weakAgainst: ['Fighting', 'Grass', 'Ground', 'Steel', 'Water'],
        immuneTo: [],
    },
    steel: {
        color: '#B7B7CE',
        veryEffective: ['Fairy', 'Ice', 'Rock'],
        notVeryEffective: ['Electric', 'Fire', 'Steel', 'Water'],
        weakAgainst: ['Fighting', 'Fire', 'Ground'],
        immuneTo: ['Poison'],
    },
    water: {
        color: '#6390F0',
        veryEffective: ['Fire', 'Ground', 'Rock'],
        notVeryEffective: ['Dragon', 'Grass', 'Water'],
        weakAgainst: ['Electric', 'Grass'],
        immuneTo: [],
    },
}